steps:
  # Step 1: Resolve dependencies
  - name: 'maven:3.8.5-openjdk-17'
    entrypoint: mvn
    args: ['dependency:resolve']
    dir: 'ProCounsellor'

  # Step 2: Build JAR
  - name: 'maven:3.8.5-openjdk-17'
    entrypoint: mvn
    args: ['clean', 'package', '-DskipTests']
    dir: 'ProCounsellor'

  # Step 3: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/procounsellor-backend-repo/backend:$COMMIT_SHA'
      - '-f'
      - 'ProCounsellor/Dockerfile'
      - 'ProCounsellor/'

  # Step 4: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/procounsellor-backend-repo/backend:$COMMIT_SHA'

  # Step 5: Deploy to Cloud Run with service name substitution
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'  # 👈 substitution here
      - '--image'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/procounsellor-backend-repo/backend:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-south1'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--max-instances=3'

substitutions:
  _PROJECT_ID: "procounsellor-71824"
  _SERVICE_NAME: "procounsellor-backend"  # 👈 default for main branch

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/procounsellor-backend-repo/backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
